/*
** ###################################################################
**     THIS MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Contents  :
**         Function "MCU_init" initializes selected peripherals.
**            By default it is empty. Select "Generate Code"
**            to produce initialization code.
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################
*/

#ifndef __mcuinit_H
#define __mcuinit_H 1

#include <hidef.h>     
#include "derivative.h"
#include "hal_system.h" 
#include "global.h"
#include "hal_adc.h"
#include "hal_can.h"
#include "hal_ect.h"
#include "hal_int.h"
#include "hal_port.h"  
#include "hal_pwm.h"  
#include "hal_spi.h"
#include "protocol.h" 







/* User declarations and definitions */
/*   Code, declarations and definitions here will be preserved during code generation */
/* End of user declarations and definitions */

extern void MCU_init(void);
/*
** ===================================================================
**     Method      :  MCU_init
**
**     Description :
**         Device initialization code for selected peripherals.
** ===================================================================
*/


/* END mcuinit */
#define VERSIONS_MAJOR	(1u)
#define VERSIONS_MINOR	(0u)
#define CAN_BL_APP		(1u)



#endif

/*
** ###################################################################
**
**     This file was created by Processor Expert
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
